### ISSUE TITLE
pipex checklist

### ISSUE THREAD

**Issue by herbievine** [herbievine/42#11]
Steps still needed for pipex:

- [ ] Fix problem with uninitialised values (warning by Valgrind)
- [ ] Find a solution to clear `pipex->cmd_args` (problem because 
`pipex->cmd_args[0][0]` can be NULL)
- [ ] Fix `unlink` command in cleanup funtion
- [x] Fix weird `here_doc` Segmentation Error

**Comment by herbievine** [comment]
Checklist moved within PR #10
